window.portfolioProjects = [
  { title: "Sales Performance Dashboard using Excel", tool: "Excel", domain: "Sales & Business Analytics / Sales Tracking", year: "2026", summary: "Interactive sales tracking dashboard for revenue, products, regions, and monthly performance.", description: "A sales analytics project that turns transaction data into a clear view of revenue, product performance, and business trends.", images: ["assets/projects/sales-dashboard/preview-1.svg", "assets/projects/sales-dashboard/preview-2.svg", "assets/projects/sales-dashboard/preview-3.svg"], live: "https://github.com/nirbhay266" },
  { title: "Python Data Toolkit", tool: "Python", domain: "Automation & Data Cleaning", year: "2026", summary: "Reusable scripts for cleaning, transforming, and exploring datasets.", description: "A collection of beginner-friendly Python utilities for loading files, checking data quality, transforming columns, and producing quick exploratory summaries.", images: ["assets/projects/sales-dashboard/preview-2.svg"], live: "https://github.com/" },
  { title: "SQL Ad-Hoc Insights Project", tool: "SQL", domain: "Data Analysis Using SQL", year: "2026", summary: "Business queries answering practical questions about customers, sales, and operations.", description: "A SQL case study organized around stakeholder questions, from top customers and repeat purchases to monthly growth and category performance.", images: ["assets/projects/sales-dashboard/preview-3.svg"], live: "https://github.com/nirbhay266" },
  { title: "Blinkit Sales & Customer Insights Dashboard", tool: "Power BI", domain: "Blinkit Sales Insights", year: "2025", summary: "A dashboard that surfaces sales trends, customer segments, and performance opportunities.", description: "An analytical view of sales and customer insights designed to help teams understand performance and prioritize action.", images: ["assets/projects/sales-dashboard/preview-1.svg"], live: "https://app.powerbi.com/" },
  { title: "Finance Tracker", tool: "Excel", domain: "Financial Planning", year: "2025", summary: "A clean workbook for tracking income, expenses, and monthly budgets.", description: "An Excel project using formulas, validation, and clear visuals to make personal or small-business financial planning easier to follow.", images: ["assets/projects/sales-dashboard/preview-2.svg"], live: "https://github.com/" },
  { title: "Portfolio Website", tool: "Python", domain: "Web Development", year: "2026", summary: "A responsive portfolio that documents projects and learning progress.", description: "A static, responsive website with a project catalogue, case-study drawer, resume download, social links, and configurable media sections.", images: ["assets/projects/sales-dashboard/preview-3.svg"], live: "https://github.com/" },
  { title: "Operations KPI Report", tool: "Power BI", domain: "Operations Analytics", year: "2025", summary: "A management report for monitoring service levels and team performance.", description: "A dashboard concept that brings operational KPIs, exceptions, and trends into one practical view for weekly reviews.", images: ["assets/projects/sales-dashboard/preview-1.svg"], live: "https://app.powerbi.com/" },
  { title: "Data Exploration Notebook", tool: "Python", domain: "Exploratory Analysis", year: "2025", summary: "A notebook for asking questions of a new dataset before dashboarding.", description: "An exploration workflow covering missing values, distributions, relationships, and the observations that should guide the next analysis.", images: ["assets/projects/sales-dashboard/preview-2.svg"], live: "https://github.com/" }
];
